<a href="https://colab.research.google.com/github/mohimrahaman/bme-research-prep/blob/main/Day_2_NumPy_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# Create a 1D array with numbers from 0 to 11
array_1d = np.arange(12)
print("Original 1D Array:\n", array_1d)

# Reshape into 3 rows and 4 columns
matrix_3x4 = array_1d.reshape(3, 4)
print("\nReshaped to 3x4 Matrix:\n", matrix_3x4)

# Reshape into 4 rows and 3 columns
matrix_4x3 = array_1d.reshape(4, 3)
print("\nReshaped to 4x3 Matrix:\n", matrix_4x3)

Original 1D Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped to 3x4 Matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped to 4x3 Matrix:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [3]:
# Create two 2x2 matrices
matrix_A = np.array([[1, 2], [3, 4]])
matrix_B = np.array([[5, 6], [7, 8]])

print("Matrix A:\n", matrix_A)
print("\nMatrix B:\n", matrix_B)

# Element-wise addition
add_result = matrix_A + matrix_B
print("\nElement-wise Addition (A + B):\n", add_result)

# Element-wise multiplication
mul_result = matrix_A * matrix_B
print("\nElement-wise Multiplication (A * B):\n", mul_result)

Matrix A:
 [[1 2]
 [3 4]]

Matrix B:
 [[5 6]
 [7 8]]

Element-wise Addition (A + B):
 [[ 6  8]
 [10 12]]

Element-wise Multiplication (A * B):
 [[ 5 12]
 [21 32]]


In [4]:
# Create a 3x3 matrix
matrix_3x3 = np.array([[10, 20, 30],
                       [40, 50, 60],
                       [70, 80, 90]])

# Create a 1D array (vector) with 3 elements
vector = np.array([1, 2, 3])

print("3x3 Matrix:\n", matrix_3x3)
print("\n1D Vector:\n", vector)

# Broadcast addition: the vector is added to EACH row of the matrix automatically
broadcast_result = matrix_3x3 + vector
print("\nResult of Broadcasting (Matrix + Vector):\n", broadcast_result)

3x3 Matrix:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

1D Vector:
 [1 2 3]

Result of Broadcasting (Matrix + Vector):
 [[11 22 33]
 [41 52 63]
 [71 82 93]]
